### ISSUE TITLE
[배경 이미지 및 프로필 이미지 최적화] 현재 프로젝트에서 이미지가 너무 늦게 업로드 되는 경우가 있어요.

### ISSUE THREAD

**Issue by D5ng** [D5ng/part2-6team-project#67]
# 현재 프로젝트에서 이미지가 너무 늦게 뜨는 현상이 발생합니다.

아직 많이 찾아보진 못했지만, 현재 제 생각으로서의 최적화는 코드잇 서버에서 전해주는 이미지를 사용하지 않는 방법이에요.
왜냐하면 코드잇 서버에서 보내주는 이미지 자체가 너무나도 높은 고해상도이기 때문에 아에 사용하지 않는 방법이 최선이라고 봅니다.

따라서 문제점을 해결하려면 unsplash 이미지에서 낮은 해상도를 사용해 이미지가 늦게 뜨는 현상을 방지할 수 있다고 생각합니다.
이외에 다양한 이미지 처리기법을 사용하고싶지만 로컬에서 불러오는 데이터라면 이미지 블러처리를 사용해 스켈레톤 UI와 비슷하게 구현할 수 있지만 현재 상황에서는 이 방법이 어렵다라고 판단이 되네요.

각자 이미지 처리기법에 대해 찾아봐보시고 좋은 방법이 있다면 알려주세요.

**Comment by dali1999** [comment]
아니면 unsplash 랜덤 이미지들을 원래 코드잇 이미지 부분에 보여주는것도 좋아보입니다.
